#!/usr/bin/env bash
#mundofile
FILE=./school
if test -e "$FILE"; then
    echo "school file exists"
    if test -f "$FILE"; then
        echo "school is a regular file"   
        if [ -s $FILE ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    else
        if [ -s $FILE ]; then
            echo "school file is not empty"
        else
            echo "school file is empty"
        fi
    fi
else
    echo "school file does not exist"
fi