#!/usr/bin/env bash
# UWU HAP

apt-get update
apt-get -y upgrade
apt-get -y install haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
cat <<EOT > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
frontend http-in
    bind *:80
    default_backend servers
backend servers
    balance roundrobin
    server web-01 5580-web-01:80 check
    server web-02 5580-web-02:80 check
EOT
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
systemctl enable haproxy
systemctl start haproxy
